### ISSUE TITLE
How to customize trailingIcon widget of FocusedMenuItem?

### ISSUE THREAD

**Issue by erguncengiz** [retroportalstudio/focused_menu#15]
I want to change trailing Icon as i want, the widget that "trailing Icon" get only "Icon" widget, but i want to add "Container" widget. How can i do that?

**Comment by NTMS2017** [comment]
Hi,

Thanks for great plugin. I have a similar question. How can I add on Appbar right side icon. Icon has onTab function but it doesn't open the focused menu widget. Any example for this or any idea how can I accomplish this problem. Thanks

**Comment by henriquezanfa** [comment]
I'm closing this issue since we added this feature on PR #19
