### ISSUE TITLE
Migrate focused_menu to null safety

### ISSUE THREAD

**Issue by peterwvj** [retroportalstudio/focused_menu#16]
This package should be migrated to null safety so that other apps and packages depending on it can (more easily) migrate to null safety as well.

Do you have any plans for this?

Thanks.

Related links:

https://dart.dev/null-safety/migration-guide

https://www.youtube.com/watch?v=bvq7wbn4VAA&ab_channel=Flutter

**Comment by peterwvj** [comment]
@retroportalstudio thanks! Will you help out with the release of the package?

**Comment by retroportalstudio** [comment]
Already did! It is available on pub.dev now

**Comment by peterwvj** [comment]
That was fast, thank you very much :)
