### ISSUE TITLE
onLongPress

### ISSUE THREAD

**Issue by Annelein** [retroportalstudio/focused_menu#9]
Hi there,

I was wondering if it is possible to use the package without having to longpress a button?

I want to have the focused_menu pop up after just one click but not sure how to do this or if this is possible?

Sorry for creating an issue for this but wasn't sure how to ask this question otherwise!

Thanks in advance

**Comment by joaovperin** [comment]
Already done on #8

**Comment by retroportalstudio** [comment]
Merged!
